### ISSUE TITLE
this.handlechange issues with mobile

### ISSUE THREAD

**Issue by project-fora** [RIP21/react-simplemde-editor#100]
Hi!

A pretty persisting issue is that on mobile (android specifically), the editor does not register text input while typing, it only registers it once spacebar or newline/return is hit. Also the cursor seems to go crazy when you try to move it mid composition, I assume as a byproduct of this.

This issue is even evident on [the demo](http://react-simplemde-edtior.netlify.com). To prove it; 
Simply write down some letters, and proceed to press bold (or any style button).
On PC, the bold syntax appears after the text, as it should.
eg: New text is fun****
On mobile, the bold syntax replaces the text, as the text being composed wasn't registered into the state for some reason.
eg: New text is ****

This creates a larger issue with user-based submissions where when posting on Android, pressing submit would publish the whole submission, except the final word.
On PC
eg: This is awesome!
On mobile
eg: This is

I have managed to narrow down the issue to the this.handlechange function. I definitely know it's not a react or mobile issue in general because draft.js, react-timepicker and redux-form's handlechange functions do not have this issue.

**Tested on:**
Android (Google Chrome)
iOS (Chrome & Safari)

**Evident on:**
Google Chrome Android

**Side Note:**
While this issue isn't evident on iOS, a different issue pops up when the same test is applied. The cursors snaps to the beginning of the line.
eg: the cursor is this caret here^
eg: ^the cursor is this caret here****

**Comment by fsoubes** [comment]
any update or custom solution ?
