### ISSUE TITLE
Cursor moving back to the beggining

### ISSUE THREAD

**Issue by isaacSolano** [RIP21/react-simplemde-editor#116]
Hi, when I add a default value to the editor, suddenly and randomly it moves the cursor back to the beginning 

![image](https://user-images.githubusercontent.com/35480414/74759292-2cb91b00-523e-11ea-8b30-b4c03aee75e5.png)

That's the way I have the code snippet, any help please

**Comment by RIP21** [comment]
Codesandox with repo will be nice to have. This is a super narrow context to triage the issue.

**Comment by isaacSolano** [comment]
Like I literally have the same example as you but in my case, the editor puts the cursor on the beginning when the default value is added(which is an html code parsed to markdown) and sometimes when I try to add _bold_ or _italic_, add them more than once, this is on React version 16.12.0, dunno what else you can have to check since it is the same as the documentation has...

**Comment by isaacSolano** [comment]
Or maybe any other tool that will actually work anybody can recommend?

**Comment by RIP21** [comment]
Context is important, if it's rendered inside some other component that rerenders often or for some reason mounts and unmounts (e.g wrong key prop usage) it may lead to following behavior. Even if code is 1:1 to the one that i have here.

**Comment by isaacSolano** [comment]
And how can I avoid that behavior with a default text value which needs to be updating constantly?

**Comment by RIP21** [comment]
I don't know, probably it can be fixed from inside of the editor. I don't have time for that, unfortunately.

I can only recommend hacking around it somehow, so this reset will not happen, or just a PR with the fix will be nice, I'll publish fix immediately.
