### ISSUE TITLE
how to upload local img to display

### ISSUE THREAD

**Issue by ainuo5213** [RIP21/react-simplemde-editor#123]
I want to upload local img in the editor to display and preview, but I don't know how to do this

**Comment by RIP21** [comment]
I'm unsure how to do that, probably for preview some hack with data:// may help. But if I'm not wrong, you should upload that to the server, server should generate a link for the image and get it back to you so you can inject it to the img as a source.
I'm not super familiar with Web file API TBH, and never had a chance to implement proper  file upload in projects that I worked in my entire life so it's all I can suggest here.

**Comment by btzr-io** [comment]
You need to create a custom `image-upload` button on the toolbar.

This is how you can get the url of the image from file:

https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications#Example_Using_object_URLs_to_display_images

**Comment by RIP21** [comment]
I think this one is pretty much answered :)
