### ISSUE TITLE
minHeight doesn't seem to work

### ISSUE THREAD

**Issue by SlyDeGout** [RIP21/react-simplemde-editor#127]
Hello,

That seems so little to do, but I can't change the height of the editor : I tried <SimpleMDE options={{ minHeight: "100px" }} /> ( even <SimpleMDE minHeight="100px" /> ) but the height isn't changing.

I can't find any information about that problem on Google, so I wonder if I'm the only one ( or the first ? ) or if I do it wrong ?

Help would be very kind, it's a big matter for the design of our pages using it.

Thanks,
Sylvain

**Comment by RIP21** [comment]
Unsure, but maybe just wrapping the whole thing in the div and set maxHeight there may help? Lazy to try out now myself. But just as an idea :)

**Comment by SlyDeGout** [comment]
Thanks for answering :)

Adding this piece of css is working 👍 
.CodeMirror-scroll,
.CodeMirror-wrap {
  min-height: 100px;
}
Even so it enforces all of the instances to have the same min-height value and it wasn't the design plan but hey, it's better than nothing and might help someone else.

This is still a bug because simplemde-editor accepts "minHeight" as an option ( or it's a bug of simplemde but lazy to try out now myself ^^ )

**Comment by RIP21** [comment]
@SlyDeGout someday I'll have time to actually fix them all :D But it won't be in 2020 I assume :D

**Comment by LiaoHanwen** [comment]
My editor works. I think maybe some other settings limit the height of the editor in your case.

```
<SimpleMDE onChange={this.props.changeMarkdown} options={{ minHeight: '100px' }} />
```

**Comment by RIP21** [comment]
Closed as more likely unactionable from my side.
