### ISSUE TITLE
how to close cm-spell-error ?

### ISSUE THREAD

**Issue by zhengpq** [RIP21/react-simplemde-editor#130]
![image](https://user-images.githubusercontent.com/24761793/83969753-42913f80-a904-11ea-9433-5be0fa3e3f13.png)

this word error reminder function does not support Chinese, is there any way to close  this function， now i use css to overwrite the style, it would be better if there is an option to close this function

**Comment by RIP21** [comment]
Try 
```
options={{
  spellChecker: false
}}
```

**Comment by zhengpq** [comment]
@RIP21  it works, thank you so much !
