### ISSUE TITLE
Unwanted Scroll Bar

### ISSUE THREAD

**Issue by Poncirus** [RIP21/react-simplemde-editor#131]
Hi,

When the content height exceeds the height of the editor, although the editor is stretched, the scroll bar appears.
![image](https://user-images.githubusercontent.com/34835605/84613760-0d4f9900-ae92-11ea-8625-ea0464a5cfc0.png)
In your [website demo](https://react-simplemde-edtior.netlify.app/), it works perfectly. However, when I clone your repo and build by myself, the problem occurs.

**Comment by RIP21** [comment]
I guess you have a strict height of the container set? You should use min-height instead of height.
