### ISSUE TITLE
Is there a way to delete the text I've entered?

### ISSUE THREAD

**Issue by kito-chall** [RIP21/react-simplemde-editor#139]
### What are you trying to do
I want to delete all text entered into SimpleMDE.
Because I am creating a chat, and in chat, I need to delete (initialize) the text after sending a message, or it will be bad UX.

I'm using next.js.
If it is a normal text area
You can easily manipulate the ```text (value)``` displayed in the browser using the```state``` as shown below.
```
const [text, setText] = useState('')
const handleClearText = () => setText('')

return (
  <div>
    <input type="button" value="Clear" onClick={handleClearText} />
    <textarea
        value={text}
        onChange={(e)=>setTest(e.target.value)}
     />
  </div>
)
```
Is there a feature in SimpleMDE that corresponds to handleClearText?

### What I've tried.
Setting state to the value of SimpleMDE only reflects the initialization phase.
When the text is entered, the state effect is lost.
```
## bad
const [text, setText] = useState('')
const changeText = value => setText(value)
const handleClearText = () => setText('')    // <- doesn't make sense

return (
  <div>
      <input type="button" value="Clear" onClick={handleClearText} />
      <SimpleMDE 
        onChange={changeText}
        value={text}
      />
  </div>
)
```

Thanks,

**Comment by RIP21** [comment]
This has been fixed in `5.0.0` please update and note breaking changes.
