### ISSUE TITLE
Most of my fa icons are not working

### ISSUE THREAD

**Issue by smooth1884** [RIP21/react-simplemde-editor#140]
Once I get on the page where I implemented the editor, most of my fa icons are showing up as a square. But only one I go onto the page where the md editor is. Then again, not all of my icons are affected. I will change them now but just wondering why this is happening...

This is the code I use for my own icons. 
`  <i className="fa fa-sign-out-alt header-icons"></i>`
`.header-icons {
  padding-left: 20%;
  color: #262626;
  display: inline;
}`

**Comment by RIP21** [comment]
The only guess I have is that for some reason CSS of fa icons are getting removed from the page when you move from page to page so there is no font for these class names to actually apply something meaningful and not squares. Double-check that.

**Comment by RIP21** [comment]
I'm closing this one as not actionable.
