### ISSUE TITLE
[Help] How To Disable Preview Mode Completely

### ISSUE THREAD

**Issue by Royal-lobster** [RIP21/react-simplemde-editor#144]
Sorry if this is dumb. I searched a lot on this and I was unable to find any solution. 
When I pass `toolbar: false` to `options` the toolbar goes away fine but it goes to preview mode and the text is unable to edit. Even the shortcut is not working when toolbar is set to false. is there any option to make the `togglePreview` always set to edit mode instead of going to preview mode ?

**Comment by Royal-lobster** [comment]
The webpage i am working on : [https://notrix.netlify.app/notes/967qpe360djekutt7rgmtj](https://notrix.netlify.app/notes/967qpe360djekutt7rgmtj)

In that, users need to click on the eye button to edit the notes. I want it to directly go to edit mode.

I want the editor to be like the last editor in this demo : [https://simplemde.com/](https://simplemde.com/)

**Comment by btzr-io** [comment]
>  the toolbar goes away fine but it goes to preview mode and the text is unable to edit

That's not the default behavior. Setting `toolbar`  to false will just hide the toolbar. Please check your code or provide more information.

**Comment by Royal-lobster** [comment]
Sorry i am dumb. I copy pasted the code in documentation without understanding it
 `getMdeInstance={(instance) => instance.togglePreview()}` 
Removing that solved issue for me.
