### ISSUE TITLE
Preview not working in NextJS

### ISSUE THREAD

**Issue by RobertBrunhage** [RIP21/react-simplemde-editor#148]
So everything works except for there is no style for the preview window and in the editing view the style is there.

![image](https://user-images.githubusercontent.com/26344867/113671301-77059180-96b6-11eb-9b6f-1e9881cae8b3.png)

This is the code I use, any help would be greatly appreciated this lib is the closest I've gotten for Nextjs readme editor!

```
import dynamic from "next/dynamic";
import "easymde/dist/easymde.min.css";


const SimpleMDE = dynamic(() => import("react-simplemde-editor"), { ssr: false })

interface ReadmeEditorProps {
    value: string,
    onChange: (value: string) => void,
}
export function ReadmeEditor({ value, onChange }: ReadmeEditorProps) {

    return (
        <SimpleMDE
            options={{
                spellChecker: false,
                sideBySideFullscreen: false,
            }}
            value={value}
            onChange={onChange} />
    );
}
```

**Comment by RobertBrunhage** [comment]
Fixed it, seemd to be about tailwind not having styles for h1 etc!

**Comment by cre8ture** [comment]
hello, can i ask how you solved this? I tried to add definitions for h1 in my global css but this did not work... somewhat new to nextjs. thank you

**Comment by necimye** [comment]
`@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  h1 {
    @apply text-2xl;
  }
  h2 {
    @apply text-xl;
  }
`
Add this to your index.css file.

**Comment by jaredweinfurtner** [comment]
> `@tailwind base; [@tailwind](https://github.com/tailwind) components; [@tailwind](https://github.com/tailwind) utilities;
> 
> [@layer](https://github.com/layer) base { h1 { [@apply](https://github.com/apply) text-2xl; } h2 { [@apply](https://github.com/apply) text-xl; } ` Add this to your index.css file.

A better option would be to add the `tailwindcss/typography` plugin and target the specific `EasyMDE` classes with `prose`.  This will also format `<p>`, `<ul>`, `<ol>`, etc.

input.css
```
@plugin "@tailwindcss/typography";
@layer base {
    .editor-preview-active, .editor-preview-active-side {
        @apply prose max-w-none;
    }
}
```
