### ISSUE TITLE
Editor can't handle `---`

### ISSUE THREAD

**Issue by RobertBrunhage** [RIP21/react-simplemde-editor#149]
![image](https://user-images.githubusercontent.com/26344867/113676111-5a6c5800-96bc-11eb-8acb-4ace8d2d9f9f.png)

As you can see when I am using --- which is pretty common for metadata, the last one (description in this case) will be larger if it splits to 2 lines, any idea on how to fix this?

Inspecting in devtools I can see that a class has been applied:
![image](https://user-images.githubusercontent.com/26344867/113676510-ccdd3800-96bc-11eb-8f1f-c5e71b2d3914.png)

**Comment by RIP21** [comment]
@RobertBrunhage hey mate.
It's not related to this project but to easymde itself. 
https://github.com/Ionaru/easy-markdown-editor
Try to find and raise an issue there instead. Thanks!
Below is the proof that it also happens in the original easymde (obviously as this project just wraps around it)
![image](https://user-images.githubusercontent.com/3940079/117582107-9c941980-b100-11eb-8447-f54593857aa7.png)
