### ISSUE TITLE
Package homepage links to IP collection/scam site

### ISSUE THREAD

**Issue by Zandor300** [RIP21/react-simplemde-editor#154]
Clicking on the link that is currently in the [package.json](https://github.com/RIP21/react-simplemde-editor/blob/75657efb1a83649cbb4e23414845ecf6ff843062/package.json) links to some kind of IP collection/scam site.

I'm in the Netherlands and for me it linked to a fake copy of [ad.nl](https://ad.nl) which is a Dutch news site, after having been redirected a couple of times where my IP is probably collected. The ad.nl page contained a Bitcoin scam.

**Comment by RIP21** [comment]
Nice catch. It used to be a website of the original author, so it's probably abandoned. I'll remove it and replace with github page with the demo.

**Comment by RIP21** [comment]
Fixed. Thanks!
