### ISSUE TITLE
TypeError: _this.simpleMde.codemirror is undefined

### ISSUE THREAD

**Issue by A7U** [RIP21/react-simplemde-editor#157]
I'm not sure why, but this keeps happening. 

```js
import SimpleMDEReact from "react-simplemde-editor";
import "easymde/dist/easymde.min.css";

export default function MK() {
    return(<SimpleMDEReact/>)
}
```
I'm on NextJS but it's a framework on top of react, so it should work with nextjs too right?

**Comment by RIP21** [comment]
I wouldn't recommend rendering SimpleMDEReact in the SSR environment, it makes no sense. You should guard it with some `isSsr` boolean so it renders on the client only.

Here are examples.
https://github.com/RIP21/react-simplemde-editor/issues/148
https://github.com/RIP21/react-simplemde-editor/issues/89
https://github.com/RIP21/react-simplemde-editor/issues/73
