### ISSUE TITLE
Enabling VIM bindings through CodeMirror's VIM API

### ISSUE THREAD

**Issue by kndwin** [RIP21/react-simplemde-editor#168]
I'm trying to set this up but having difficulty. Wondering if someone could help / if it's not possible yet, if there's any room in the roadmap for this request? 

I know we have "extraKeys" and can overide it, but i'm struggling at the moment on knowing where to add the "keymap/vim.js" file as per the docs.

Related documentation: https://codemirror.net/doc/manual.html#vimapi

Happy if this isn't supported, just thought I'll shoot my shot

**Comment by RIP21** [comment]
Hey mate. It's out of the scope of this project. It's a tiny wrapper around the `easymde` that syncs React state with easymde and its mount/unmount etc., everything related to its underlying thingy e.g. codemirror, and `easymde` nuances are 99% cases for opening an issue/discission on their side :)
