### ISSUE TITLE
How to parse math formulas with katex?

### ISSUE THREAD

**Issue by henrique-barreto** [RIP21/react-simplemde-editor#169]
Hello, 

how can I add a katex parser to the editor, just like [Stackedit.js](https://github.com/benweet/stackedit)?

> StackEdit renders mathematics from LaTeX expressions inside your markdown file.

![Screenshot from 2021-07-29 19-55-29](https://user-images.githubusercontent.com/20756536/127575849-d27293b9-2540-4f22-a4fb-d7a2f3143641.png)

**Comment by btzr-io** [comment]
You will probably need a custom markdown preview:
https://github.com/RIP21/react-simplemde-editor#custom-preview-rendering-example

**Comment by btzr-io** [comment]
https://github.com/remarkjs/remark-math

**Comment by RIP21** [comment]
@btzr-io exactly. You're right :)
