### ISSUE TITLE
Make markdown renderer use JSX Element

### ISSUE THREAD

**Issue by croumegous** [RIP21/react-simplemde-editor#171]
Hello,

I'd like to know if there is any solution or workaround to use JSX Element with a custom preview.

My code currently look like this:

```ts
...
let renderer = new marked.Renderer();
  renderer.em = function (text) { // error : Type 'Element' is not assignable to type 'string'.
    return (
      <NoteTimestamp
        timestamp={60}
        text={"1:00"}
        playerRef={playerRef}
      ></NoteTimestamp>
    );
  };
  //Editor Options
  const MDOptions = useMemo(() => {
    return {      
      spellChecker: false,
      sideBySideFullscreen: false,
      renderingConfig: {
        markedOptions: {
          renderer: renderer,
        },
      },    
    };
  }, []);

  return (    
      <SimpleMdeReact
        id="note"
        value={value}
        onChange={onChange}
        options={MDOptions}
      />
    </div>
  );
```
And NoteTimestamp.tsx :
```ts
...
return (
    <span
      className={
        "cursor-pointer text-nx-red"
      }
      onClick={() => setCurrentTime(timestamp / 1000)}
    >
      {text}
    </span>
  );
  ```
But it doesn't work as renderer.em expect a string.

For more context the markdown component is next to a video player and in the preview I need to have the timestamp of the video which  is clickable and onClick it change the current timestamp of the video (with setCurrentTime).

I've tried using ReactDomServer.renderToString() but it does not work.
I've also tried to use : 
```ts
renderer.em = function (text) {
    return `<a  href="#" onclick="${setCurrentTime(timestamp)}">${text}</a>`; 
```
directly in the main file (without using tsx Element), however in the final HTML page the onclick function is undefined as it doesn't interpret the TSX part.

**Comment by RIP21** [comment]
I haven't done it myself, to preview it right in the editor nicely, but after you've got markdown you can make a preview (like in example in Readme) and so if you can do preview, it means you can render whatever you like later using pretty similar code using https://github.com/remarkjs/react-markdown

How to setup react-markdown and hack it so on click handlers are working probably is none of my business :)

I wouldn't change rendering config of the marked that's for sure. I would do all the things later at the rendering of markdown string.

**Comment by croumegous** [comment]
Thanks for the quick response, it will be handy.  
I will close the issue for the moment, and post a code example if I achieved to make it work properly.
