### ISSUE TITLE
The cursor changes position by itself

### ISSUE THREAD

**Issue by vikshv** [RIP21/react-simplemde-editor#179]
versions. 5.00 and 5.0.2
react/react-dom: 16.8.6
"Controlled usage" example

hold down the key -> the cursor goes to the beginning

on version 4.1.5 is not reproduced

**Comment by nscarlson** [comment]
> I suspect that it's because I forgot to wrap onChange in useCallback so "new" onChange handler causes this behavior. Please try that and let me know if it will fix your issue.
> 
> Changed README respectively

Confirmed the same issue on `react-simplemde-editor` version `5.0.1` with the `onChange` function wrapped in `useCallback`.

**Comment by RIP21** [comment]
Cannot reproduce. You can check yourself how demo is working.
