### ISSUE TITLE
Cursor disappears after typing a letter

### ISSUE THREAD

**Issue by ANJALI2980** [RIP21/react-simplemde-editor#188]
React : v17.0.2
Simplemde : v5.0.2

Description:
I am very  new to Simplemde.I used Simplemde in my react project.when I am trying to type into text area of Simplemde the cursor disappears after typing a single letter,to type next letter I had to click on textarea to bring back cursor.
I tried but couldn't find solution.

Code:
imports:
import React, { Component } from 'react';
import SimpleMDE from "react-simplemde-editor";
import "easymde/dist/easymde.min.css";

onBodyChange = (value) => {
        this.setState({
            body: value,
        });
    };

<SimpleMDE
       onChange={this.onBodyChange}
       options={{
        hideIcons: ["preview","side-by-side","fullscreen"]
     }}    
 />

![after](https://user-images.githubusercontent.com/64256935/153234923-9fdf6a38-5913-4a5b-88d0-a3bf3162f9a5.PNG)
![before](https://user-images.githubusercontent.com/64256935/153234928-77d6ae6f-4ba1-4bf4-a7c0-74a14c1e6995.PNG)

**Comment by RIP21** [comment]
@ANJALI2980 hey. I see that your code example is not full. So I cannot help much. I need more.

**Comment by ANJALI2980** [comment]
@RIP21 my issue is mentioned in issue #164 .you suggested to memoize options but I am not sure how to do that,please help!

**Comment by RIP21** [comment]
Take a look at the `README.md`. 

Memoize = use `useMemo` hook.
E.g. `const options = useMemo(() => { return {  ideIcons: ["preview","side-by-side","fullscreen"] }}, [])`
And then `options={options}` below in JSX.

In case you're using `class` component, you need to have property like

```
editorOptions = {
	hideIcons: ["preview","side-by-side","fullscreen"]
}
```
inside your class body.
Then you'll use it in the component the same way you use `onChange` handler. E.g. `options={this.editorOptions}`

**Comment by zhang-xiaoyu-X** [comment]
Thanks! This issus enabled me to solve 2 problems.
Note 1: If you don't memoize options on each render，the focus will be lost.
Note 2: if you don't specify a custom id, it will automatically generate an id for you.

**Comment by jcwrightson** [comment]
I had the same problem. Fixed by setting `autofocus: true` in the editor options.

**Comment by felixroos** [comment]
a simpler solution: it will also work if you define the options statically outside of the component, as the object will stay the same:

```js
const mdeOptions = {/*...*/}

function MyComponent() {
  /* ... */
  return (<SimpleMDE options={mdeOptions} value={value} onChange={onChange} />)
}
```

**Comment by Hassan-Khan16** [comment]
> I had the same problem. Fixed by setting `autofocus: true` in the editor options.

Yoooo, You helped me a lot. Also thank you @RIP21 for the amazing library. I was using ReactMde and switch to simpleMDE and loved it
