### ISSUE TITLE
Toolbar buttons not displaying correctly

### ISSUE THREAD

**Issue by kelokchan** [RIP21/react-simplemde-editor#204]
What's happening with the toolbar? It seems that the CSS got messed up and the toolbar buttons are no longer showing

![image](https://user-images.githubusercontent.com/5347725/182748339-f6fc2937-aec8-47cd-8b9b-d552f0dcf5db.png)

**Comment by RIP21** [comment]
You probably forgot to import CSS or somehow your CSS loader is broken.

Don't forget to 

`import "easymde/dist/easymde.min.css";`
