### ISSUE TITLE
./node_modules/react-simplemde-editor/dist/SimpleMdeReact.mjs

### ISSUE THREAD

**Issue by dheerajstageconnect** [RIP21/react-simplemde-editor#208]
./node_modules/react-simplemde-editor/dist/SimpleMdeReact.mjs
 Can't import the named export 'useCallback' from non EcmaScript module (only default export is available)
2022-10-04T07:16:45.829Z [WARNING]: error Command failed with exit code 1.

**Comment by EvertonMJunior** [comment]
Hey @dheerajstageconnect, how did you solve this? I'm having the same issue
