### ISSUE TITLE
Not working internal link in README.md 

### ISSUE THREAD

**Issue by live-small** [RIP21/react-simplemde-editor#211]
## problem
In README.md, Not working link that title is "Retrieve easymde, codemirror or cursor info to be able to manipulate it." `line: 22`

<img width="1389" alt="스크린샷 2022-10-11 오후 5 52 21" src="https://user-images.githubusercontent.com/70274947/195044746-9ce4ccd8-1c99-40d1-a9c0-679f3311b936.png">

**current link**: https://github.com/RIP21/react-simplemde-editor#retrieve--easymde----codemirror--or--cursor--info-to-be-able-to-manipulate-it

**have to change**: https://github.com/RIP21/react-simplemde-editor#retrieve-easymde-codemirror-or-cursor-info-to-be-able-to-manipulate-it

**Comment by RIP21** [comment]
PR welcome :) You can do it through the Github UI BTW. Clicking on pencil opening README.md file.

**Comment by RIP21** [comment]
Thanks :)
