### ISSUE TITLE
How can I disable markdown AutoComplete feature?

### ISSUE THREAD

**Issue by komplamoose** [RIP21/react-simplemde-editor#214]
First of all, thank you for creating this wonderful library.

I am now creating a collaborative text editor based on CRDT.

```
1. test1 << press "enter"
2.  << AUTO COMPLETE
```
While working, I found out that this editor supports automatic completion in grammar related to markdown.
The user experience will be low, but I don't want to consider it because it's currently difficult to convert and synchronize all of these automatic generations.

Unfortunately, even after trying to Google or document, I couldn't find a way to remove this auto-complete feature.

I found a [project](https://github.com/yorkie-team/codepair) that used this library to create a similar function, but I found that it was not automatically completed.

Although I referred to the options in this project, it is being completed automatically. What should I do in this case?
I'm sorry to leave you with a silly question.

**Comment by RIP21** [comment]
Thanks!
Regarding your question, to be honest ,I have no idea. 

The only place where you may find a way to disable stuff like that is in the easymde options and in codemirror doc as this is what easymde uses under the hood. This project is just a wrapper for easy use with React, but for the most part, most of the advanced stuff is going through their docs. So you may ask such questions there or try to search their issues. 

I'll close it up for now as it's not actionable from my side, but if you'll find a solution please share it so others can learn :)
