### ISSUE TITLE
lineNumbers option prevents backspace of empty line on Mobile

### ISSUE THREAD

**Issue by alpharomercoma** [RIP21/react-simplemde-editor#216]
Found out `lineNumbers: true` option does not allow for backspace on mobile, even inside a useMemo. 

Update: just figured it's not actionable here too. Sorry, You can delete this issue. 

https://user-images.githubusercontent.com/108984668/205889656-f5d316d7-3810-4206-99eb-6e463702ae33.mp4

**Comment by RIP21** [comment]
Mother of God 61 tabs on mobile lol.

**Comment by RIP21** [comment]
And yeah, sorry, I wish I can help.
