### ISSUE TITLE
how to make this RTL ?

### ISSUE THREAD

**Issue by am0029** [RIP21/react-simplemde-editor#218]
how to make this RTL ?

**Comment by RIP21** [comment]
If easymde supports that, then it's probably possible. Check their documentation. It's nothing on the side of this react wrapper that can make it happen.

**Comment by am0029** [comment]
i can not belieave it ?!!!

how this is possible ? simple function rtl or ltr  not available !!!!!!!!!!!!

ok

**Comment by RIP21** [comment]
Read the documentation of easymde. This library is just a wrapper on top of easymde. All the customisation of the editor comes from options prop that you pass when you render it. These configuration options are coming from easymde please go to easymde documentation and check how to do RTL there.  https://github.com/Ionaru/easy-markdown-editor

**Comment by RIP21** [comment]
Here is what a simple check of the easymde docs gave me in 2 seconds.

> direction: rtl or ltr. Changes text direction to support right-to-left languages. Defaults to ltr.

**Comment by RIP21** [comment]
So, in short. You should pass options object (don't forget to have out outside of render function) with direction being "rtl" and that is it.

**Comment by RIP21** [comment]
And be polite when you ask something. Thanks.

**Comment by am0029** [comment]
i saw that before i come here . not working with react it is just simple code that not working . i do not know why 
my application is react mern stack but in their documentation just plain java script 

i do not know how to configure i just know how configure your mde sadly

because u do not respect to half of the world is rtl writhing 

it is racist
 this move \. make editor ltr and when people ask from you. you say not planned to do . ltr people best half of the world is nothing just english people can ??.

but i am sorry ok my friend .
