### ISSUE TITLE
You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by ENT108** [RIP21/react-simplemde-editor#224]
Hi,

The package wont compile:
![Screenshot 2023-06-15 at 14 22 34](https://github.com/RIP21/react-simplemde-editor/assets/25681316/8ec215ad-ab73-4881-b41e-d6889b7bb904)

This is my tsconfig:
![Screenshot 2023-06-15 at 14 23 15](https://github.com/RIP21/react-simplemde-editor/assets/25681316/9e78d1b1-2eea-402f-94d1-91a9dff57222)

Anybody had that issue?
Thanks!

**Comment by RIP21** [comment]
Use Vite instead of create-react-app (react-scripts)

React scripts are very outdated.

**Comment by daviddecentage** [comment]
Any workaround for the issue?

To use vite instead of CRA is not often feasible for legacy projects

**Comment by ENT108** [comment]
I went for Wysimark package... as a workaround.

**Comment by RIP21** [comment]
@ENT108 sorry that I never had time to investigate that.
But Wysimark actually looks better than Easy MDE so good for you TBH :) Or at least, more modern and much more compatible with React than these bindings which are a tradeoff.
