### ISSUE TITLE
toolbar does not display on MacOS

### ISSUE THREAD

**Issue by EyreGe** [RIP21/react-simplemde-editor#225]
<img width="423" alt="image" src="https://github.com/RIP21/react-simplemde-editor/assets/19946413/d760c521-bc4e-4d28-8205-d94e7a89d3d8">

<img width="240" alt="image" src="https://github.com/RIP21/react-simplemde-editor/assets/19946413/de0f03a8-3821-42e0-91b0-49f20acc4f6b">

result：

MacOS:
<img width="486" alt="image" src="https://github.com/RIP21/react-simplemde-editor/assets/19946413/d3d87621-7f12-427b-b569-d50077487f83">

Windows: normal

The same is true for running demos on MacOS：
<img width="736" alt="image" src="https://github.com/RIP21/react-simplemde-editor/assets/19946413/e4d5291b-3a55-481f-ba3d-29ee8a65fb57">

"react": "^17.0.0",
"react-simplemde-editor": "^5.2.0",
"easymde": "^2.18.0",
MacOS： 12.6

**Comment by wraeth-eth** [comment]
Having the same issue

**Comment by wraeth-eth** [comment]
Nevermind I solved it.

For me, it turned out to be a CSP issue blocking https://maxcdn.bootstrapcdn.com for the fonts
