### ISSUE TITLE
Enforce maxLength attribute

### ISSUE THREAD

**Issue by tiotdev** [RIP21/react-simplemde-editor#229]
It would be great if passing a maxLength attribute would work like in a textarea.
This does not work:
```
<SimpleMde
value={description}
onChange={handleDescriptionChange}
maxLength={1000}
/>
```
Is there any way currently to enforce the max length?

**Comment by RIP21** [comment]
If it's controlled, you can control it with a code.

But I would recommend you to look at easy mde original documentation and see if this is supported there and if so, just pass right options.

This is a lightweight wrapper on top of easy mde, there is no plans to add anything on top of what easy mde already does.

**Comment by tiotdev** [comment]
Thank you!

I got it working by using getCodemirrorInstance and modifying the codemirror instance with this code https://github.com/Ionaru/easy-markdown-editor/issues/254

**Comment by RIP21** [comment]
Glad I was able to point you to the right direction :)
