### ISSUE TITLE
Multiline Code Block Highlighting in Edit Mode

### ISSUE THREAD

**Issue by 32teeth** [RIP21/react-simplemde-editor#232]
### Issue

When creating a multi line code block in the editor the representation is really wonky
![Screenshot 2023-10-11 at 09 54 09](https://github.com/RIP21/react-simplemde-editor/assets/75797/dd3bd970-ce10-4120-92b4-877d44295a99)

### Options

1. Prevent any highlighting in edit mode (this is standard convention)
2. Highlight entire row across text

```
#!/bin/bash

# Usage: fusi-curl-report.sh [curl options]
curl -w @- -o /dev/null -s "$@" <<'EOF'
    time_namelookup:  %{time_namelookup}\n
       time_connect:  %{time_connect}\n
    time_appconnect:  %{time_appconnect}\n
   time_pretransfer:  %{time_pretransfer}\n
      time_redirect:  %{time_redirect}\n
 time_starttransfer:  %{time_starttransfer}\n
                    ----------\n
         time_total:  %{time_total}\n
EOF
```

#### GitHub Editor Mode
> No highlighting

![Screenshot 2023-10-11 at 09 54 45](https://github.com/RIP21/react-simplemde-editor/assets/75797/d1f49a49-d735-4aa1-a9ee-848ae468a5af)

**Comment by RIP21** [comment]
Look at how to style the editor styles on easymde docs or in codemirror docs that powers it. Styling is not in scope of this wrapper library.

Feel free to re-open if it makes sense. Thanks.
