### ISSUE TITLE
Using in Next.js client component caused a ReferenceError on the server when the page loads

### ISSUE THREAD

**Issue by Julian24Design** [RIP21/react-simplemde-editor#238]
### My code

<img width="652" alt="image" src="https://github.com/RIP21/react-simplemde-editor/assets/14356389/6ed0db83-0959-4bcf-b305-fe5f3a072ad6">

### The error on the terminal

<img width="1042" alt="image" src="https://github.com/RIP21/react-simplemde-editor/assets/14356389/8153490c-7918-4ccb-b817-7134388ef7a0">

**Comment by RIP21** [comment]
Try using dynamic Next.js helper with ssr: false setting and it should start to work.
https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#with-no-ssr
