### ISSUE TITLE
Does react-simplemde-editor clean up after itself?

### ISSUE THREAD

**Issue by thuey** [RIP21/react-simplemde-editor#38]
Hi, I'm considering using simplemde for a React app I'm working on. This library you've created would make that super simple! One question I have, though, is if react-simplemde-editor cleans up after itself. According to this issue: https://github.com/NextStepWebs/simplemde-markdown-editor/issues/142, there are problems with using simplemde because it leaves instances hanging around. I took a look at your source code, and at first glance, it doesn't appear to handle this automatically. Maybe I'm wrong, however.

**Comment by RIP21** [comment]
@thuey this is a dead old issue. If you have any PR to do please do.
 I took over this project.

**Comment by RIP21** [comment]
@thuey the only thing we do is a clean-up of the event listeners that we got created.

**Comment by RIP21** [comment]
@thuey I went to the issue they had, and from what I can see the issue is solved so we are pretty much safe.
