### ISSUE TITLE
The editor is totaly broken in my react/webpack project

### ISSUE THREAD

**Issue by fadehelix** [RIP21/react-simplemde-editor#48]
I try to use the component in my project. I am following the [Usage](https://github.com/benrlodge/react-simplemde-editor#usage) guide and the only thing I see are unstyled toolbar buttons.
There are also __no errors/warnings__ in the console, so I have no idea what is wrong.

This is my setup:
```
  "devDependencies": {
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "react-hot-loader": "^1.3.1",
    "webpack": "^3.0.0",
    "webpack-dev-server": "^2.5.0"
  },
  "dependencies": {
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-simplemde-editor": "^3.6.11"
  }
```

**Comment by chrisdobler** [comment]
having the same issue.

**Comment by jwelfare** [comment]
@fadehelix I had this problem as well. Including the CSS sheet (attached) manually seemed to fix it. Pretty sure you shouldn't have to, but it gets it working in the meantime. 
[styles.txt](https://github.com/benrlodge/react-simplemde-editor/files/1123439/styles.txt)

**Comment by fadehelix** [comment]
@jwelfare thanks for advice! Following your suggestion I did this:
1. Install webpack css loader: `npm i -D style-loader css-loader`
2. Import css file into my component: `require("!style-loader!css-loader!react-simplemde-editor/dist/simplemde.min.css")`

Now the editor works as expected.

**Comment by RIP21** [comment]
@fadehelix @jwelfare @chrisdobler Hi guys I took over this project. If you will have any PRs and improvements please do! I will merge them and release a new version ASAP.
Thanks.
