### ISSUE TITLE
Can I take over the project?

### ISSUE THREAD

**Issue by RIP21** [RIP21/react-simplemde-editor#49]
Hi, I quite often use this editor, and I want to keep it up. So it will be at least compatible with React 16 etc. So, @benrlodge if you fine with that, I would like to take care of it so I can merge PRs, update it myself etc.

**Comment by benrlodge** [comment]
It's yours! I tried to transfer it over to you but since you have the repo forked, it wouldn't let me. if you could rename or blow away that repo, I can try again.

**Comment by RIP21** [comment]
@benrlodge I was on vacation with almost no access to internet :) 
I already removed the fork. Once you will transfer it to me, I will make try to solve as many issues as possible :)

**Comment by tylercaldwell** [comment]
@benrlodge @rip21 is this still happening? If not, as a frequent user, I'd also be happy to take over the project :)

**Comment by RIP21** [comment]
@tylercaldwell I'm here still waiting for it :)

**Comment by benrlodge** [comment]
apologies for the delay - I just made the request @RIP21 you should be able to over ownership now

**Comment by RIP21** [comment]
@tylercaldwell If you have any PRs to do please do. I will review so we can develop this a bit further.
@benrlodge thanks a lot! I will not let your nice project down :D Need to be familiarized with build process tho. And, what about npm package? It's right now limited to you. Can you give me an access to this package there so I can deploy new versions?
Go there and add me as the collaborator. Thanks.
My nick there is **rip21**
