### ISSUE TITLE
Call for contibutors

### ISSUE THREAD

**Issue by RIP21** [RIP21/react-simplemde-editor#53]
Hi everyone. 
I took over this project from the @benrlodge to support this one more actively.

I collect here all of the most updated forks to unite all your work in one place so all of us could benefit. 

So, please.
@jwelfare
@taleship
@appsumo
@janprasil
@interviewstreet

You have few commits ahead please feel free to create PR with some explanation of what you did. I will be happy to merge them ASAP and deploy new version afterward when I will be added as a collab in NPM.

Thanks, and let's make it better :) 

React 16, better build etc is all planned. But if you have it already, I will be happy to save my time.
Thanks!

**Comment by matteing** [comment]
Hi - founder of Taleship here.

I've been doing some patches more specific to the platform and trying to fix the more glaring bugs - but nothing more substantial yet. I've been working on it actively however.

If I manage to fix anything big won't hesitate to send a patch upstream.

-
Mattei

**Comment by RIP21** [comment]
@matteing hi! Please, if you have some nice additions, go ahead and do it. Platform, code, deps whatever what will make this better.
Thanks :)

**Comment by matteing** [comment]
@rip21 i'll definitely try to upstream what I have this weekend. Thanks for reviving the project!

**Comment by janprasil** [comment]
I only added condition for `process.env.IS_BROWSER` because the server side rendering was not working for me. Also I converted the code to, in my opinion better readable, ES6. And moved react dependency to peer dependencies.

**Comment by RIP21** [comment]
ES6 + peer dependencies thing is a fine change.
So you can PR them if it's not a big deal.

**Comment by RIP21** [comment]
@janprasil just adopted your changes to the main repo. So feel free to depend directly.
version 3.6.13
Some improvements to come later.
