### ISSUE TITLE
the cursor jumps to the very beginning when editing

### ISSUE THREAD

**Issue by zhangtemplar** [RIP21/react-simplemde-editor#70]
The bug appears in 3.6.16 but not 3.6.15.

When you type something in the editor, the cursor is always jumps to the very beginning. For example, if you type `abcd`, you actually gets `dcba` in the editor.

**Comment by RIP21** [comment]
Sheeeeet, thanks guys, will take a look. As always PR welcome, but if not,
I will eventually fix it.

**Comment by nerfologist** [comment]
We are also experiencing this problem and we had to roll back to 3.6.15 for now.

**Comment by RIP21** [comment]
Hey guys, I'll fix this issue this weekend. Thanks for reporting once again and sorry for so long wait.

**Comment by RIP21** [comment]
This should be fixed by now. Try again, and if still persists please create reproduction using codesandbox.io
