### ISSUE TITLE
How do you start the default editor with the side-by-side preview panel? 

### ISSUE THREAD

**Issue by fforbeck** [RIP21/react-simplemde-editor#71]

**Comment by RIP21** [comment]
It's more question to the original SimpleMDE. Try to check out the prototype of the mde instance to find something like setPreview or togglePreview, this way you'll be able to toggle preview on mount.
Couldn't answer in detail since on vacation, sorry  🙏

**Comment by fforbeck** [comment]
thanks @RIP21
