### ISSUE TITLE
Problem with SSR in Next.js

### ISSUE THREAD

**Issue by LinusU** [RIP21/react-simplemde-editor#73]
When using this component together with [Next.js](https://github.com/zeit/next.js/), I'm running into trouble when the component is first rendered on the server.

> Cannot read property 'getElementsByClassName' of null

Currently I'm working around this by hiding the component, and only showing it after `componentDidMount`, but this is a bit annoying to have to do this every time.

I'm guessing that the problem has something to do with it trying to load SimpleMDE even on the server. It would be nice if maybe we could detect this (e.g. `typeof window`) and simply defer until `componentDidMount` have triggered.

**Comment by RIP21** [comment]
I also use it with SSR and Next.js and I don't have such issue.
I would suggest you to use.
`const SimpleMDE = dynamic(import('react-simplemde-editor'), { ssr: false })`
This way it will be rendered only on the client and also will not appear in the final bundle and will be fetched only when needed.

About detecting it on did mount etc.
This is exactly what is in the code.
```
  componentDidMount() {
    if (typeof window !== undefined) {
      this.createEditor();
      this.addEvents();
      this.addExtraKeys();
      this.getCursor();
      this.getMdeInstance();
    }
  }
```
I'm closing this one for now.
If anything I can do, tell me, please.
A code is pretty straightforward, so PR shouldn't be a problem I think.
