### ISSUE TITLE
the <SimpleMDE />  Component can't lose focus when click other <input type="text">

### ISSUE THREAD

**Issue by Ak-lee** [RIP21/react-simplemde-editor#78]
the simpleMDE Component can't lose focus when there is anoter `<input  type="text" />` in the page.
![image](https://i.loli.net/2018/12/08/5c0b865333b1a.gif)
@gammons @toneplex @captainsafia @benmliang

**Comment by toneplex** [comment]
@Ak-lee take a look at your code because this isn't an issue with SimpleMDE.  Check if they aren't named the same, autoFocus or something else forcing focus.

**Comment by Ak-lee** [comment]
> @Ak-lee take a look at your code because this isn't an issue with SimpleMDE. Check if they aren't named the same, autoFocus or something else forcing focus.

Thank you so much, I already find that causing the propblem is because of I use a `Tampermonkey` script

**Comment by RIP21** [comment]
Sorry for not answering that, but yeah, it seems that it's not our issue.
I will close the issue if you don't mind. Feel free to reopen.
