### ISSUE TITLE
Export SimpleMDEEditorProps

### ISSUE THREAD

**Issue by lucasriondel** [RIP21/react-simplemde-editor#82]
Can you export your type `SimpleMDEEditorProps` ? It would be really useful for me since I want to use styled-components on it and still have props completion afterwards.

**Comment by RIP21** [comment]
Use copy paste for now :D But will do next version (prob on weekend) with
exported props :)

czw., 17 sty 2019, 14:53: Lucas Riondel <notifications@github.com>
napisał(a):

**Comment by lucasriondel** [comment]
I was thinking about copy pasting it but it would be so clean to import it directly from you ! Thanks a lot for your quick response anyway.
