### ISSUE TITLE
Switch to upstream fork?

### ISSUE THREAD

**Issue by LinusU** [RIP21/react-simplemde-editor#85]
It seems like development has stalled on SimpleMDE, and the developers seem unresponsive. There is a number of PRs open that haven't been merged, and no commits have been made the past few years 😞 

This fork seems to be the most active one and includes some nice fixes that I would love to get in:

https://github.com/Ionaru/easy-markdown-editor

What do you think about switching to that fork?

**Comment by RIP21** [comment]
Sure thing! I'll come back to you if I'll need any help. If I'll be too
busy will be glad to share ownership.

pt., 25 sty 2019, 12:30: Linus Unnebäck <notifications@github.com>
napisał(a):

**Comment by RIP21** [comment]
Version 4 released with easymde under the hood.
Feel free to test and feedback.

**Comment by LinusU** [comment]
Will do, thanks!
